# Generated by Django 3.0.3 on 2020-02-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_D',
            fields=[
                ('PK_Course_D', models.AutoField(primary_key=True, serialize=False)),
                ('Course_ID', models.CharField(max_length=15, unique=True)),
                ('Batch_Type', models.CharField(max_length=1, null=True)),
                ('Batch', models.CharField(max_length=300, null=True)),
                ('Start_Date', models.DateField(null=True)),
                ('End_Date', models.DateField(null=True)),
                ('Duration', models.IntegerField(null=True)),
                ('Location', models.CharField(max_length=300, null=True)),
                ('Area_ID', models.CharField(max_length=3, null=True)),
                ('Number_App', models.IntegerField(null=True)),
                ('Number_People', models.IntegerField(null=True)),
                ('BudgetApp_1', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('BudgetApp_2', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('BudgetPay_1', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('BudgetPay_2', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('Key_By', models.CharField(max_length=10, null=True)),
                ('Key_Date', models.DateField(auto_now_add=True)),
                ('RegisterStatus', models.BooleanField(null=True)),
                ('RegisterType', models.CharField(max_length=15, null=True)),
                ('Start_Time', models.DateTimeField(null=True)),
                ('End_Time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MT_User',
            fields=[
                ('PK_User', models.AutoField(primary_key=True, serialize=False)),
                ('User_ID', models.CharField(max_length=10, null=True)),
                ('Division_ID', models.CharField(max_length=5, null=True)),
                ('Permit_Group', models.CharField(max_length=5, null=True)),
                ('Key_Date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='List_Emp',
            fields=[
                ('PK_List', models.AutoField(primary_key=True, serialize=False)),
                ('E_ID', models.CharField(max_length=10, null=True)),
                ('Regist_Date', models.DateField(auto_now_add=True)),
                ('ref_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='List_Emp_Course_D', to='register.Course_D')),
            ],
        ),
        migrations.CreateModel(
            name='List_Dept',
            fields=[
                ('PK_List', models.AutoField(primary_key=True, serialize=False)),
                ('ref_group', models.CharField(max_length=5, null=True)),
                ('dept', models.CharField(max_length=30, null=True)),
                ('number_dept', models.IntegerField(null=True)),
                ('number_stamp', models.IntegerField(null=True)),
                ('ref_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='List_Dept_Course_D', to='register.Course_D')),
            ],
        ),
    ]
