# Generated by Django 3.0.3 on 2020-02-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_d',
            name='CourseType_ID',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course_d',
            name='Course_Name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
