# Generated by Django 3.0.3 on 2020-02-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200219_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_emp',
            name='E_ID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
