# Generated by Django 3.0.3 on 2020-02-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20200221_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_dept',
            name='status',
            field=models.IntegerField(default=0, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='list_emp',
            name='status',
            field=models.IntegerField(default=0, max_length=1, null=True),
        ),
    ]
