# Generated by Django 3.0.3 on 2020-02-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20200225_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_dept',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='list_emp',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
