# Generated by Django 3.0.3 on 2020-02-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20200225_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_d',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
