# Generated by Django 3.0.3 on 2020-02-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_course_d_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_emp',
            name='Position',
            field=models.CharField(default='หผ.', max_length=10, null=True),
        ),
    ]
