# Generated by Django 3.0.3 on 2020-02-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_list_emp_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_emp',
            name='Level',
            field=models.CharField(default='08', max_length=2, null=True),
        ),
    ]
