# Generated by Django 3.0.3 on 2020-04-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20200226_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_emp',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
