# Generated by Django 3.0.3 on 2020-04-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_list_emp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_emp',
            name='Tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
