# Generated by Django 3.0.3 on 2020-07-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_list_emp_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_emp',
            name='Dept_code',
            field=models.CharField(blank=True, default='0000', max_length=20, null=True),
        ),
    ]
