# Generated by Django 3.0.3 on 2020-11-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_course_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_ID', models.CharField(blank=True, max_length=10, null=True)),
                ('Position', models.CharField(default='อก.', max_length=20, null=True)),
                ('Dept_code', models.CharField(blank=True, default='0000', max_length=20, null=True)),
                ('Area', models.CharField(blank=True, default='สนญ.', max_length=10, null=True)),
                ('Year', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
