# Generated by Django 3.0.3 on 2020-11-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_course_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_Loginerror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_ID', models.CharField(blank=True, max_length=10, null=True)),
                ('Case', models.CharField(blank=True, max_length=200, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
