# Generated by Django 3.0.3 on 2021-01-20 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_check_staff_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_staff_end',
            name='Update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
