# Generated by Django 3.0.3 on 2021-03-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_check_staff_end_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subject_no', models.AutoField(primary_key=True, serialize=False)),
                ('Subject_name', models.CharField(max_length=150, null=True)),
                ('Description', models.CharField(max_length=150, null=True)),
                ('Url_location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='course_d',
            name='Mc_no',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('Mc_no', models.AutoField(primary_key=True, serialize=False)),
                ('Mc_name', models.CharField(max_length=100, null=True)),
                ('Mc_level', models.IntegerField(default=1, null=True)),
                ('ref_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reference', to='register.Subject')),
            ],
        ),
    ]
