# Generated by Django 3.0.3 on 2021-03-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_auto_20210311_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mc_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ref_Mc', to='register.Competency')),
                ('Subject_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ref_sub', to='register.Subject')),
            ],
        ),
    ]
